# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'https://github.com/NeuraLabs/NeuraSwiftSDKFramework.git'


target 'NeuraTutorialSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeuraTutorialSample
  pod 'NeuraSwiftSDKFramework'
  pod 'KRProgressHUD'

  target 'NeuraTutorialSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeuraTutorialSampleUITests' do
    # Pods for testing
  end

end
